### ISSUE TITLE
package contains console outputs?

### ISSUE THREAD

**Issue by mrdjohnson** [dizco/react-scrollable-feed#110]
**Describe the bug**
When running the project the package is doing console logs like "render" or "cstr".

**Expected behavior**
Packages do not output to console log

**Screenshots**
<img width="660" alt="image" src="https://github.com/dizco/react-scrollable-feed/assets/6767910/d1018b8b-9edc-45c4-b524-916ab93d1997">

**Comment by dizco** [comment]
Please install 2.0.2
