### ISSUE TITLE
Add onScroll event

### ISSUE THREAD

**Issue by yurievangelista** [dizco/react-scrollable-feed#30]
**Is your feature request related to a problem? Please describe.**
I want to execute a specific behavior when the onScroll event of this component fires - specifically, I'd like to show a "scroll to bottom" button when the user scrolls up, and the last element goes out of view.
Currently, it seems like there is no way to do this.

**Describe the solution you'd like**
The onScroll prop could be added to the ScrollableFeed component and passed down to the main div that wraps the children. It's an easy solution that would allow us to attach a handler to this event.

**Comment by dizco** [comment]
Hry @yurievangelista, thanks for the suggestion! What would you see as parameters to that event? I'm thinking you need data on the current distance to bottom, scroll direction, etc.?
You can definitely send a PR to the repo with this feature if you would like! It will probably be a while before I can tackle this.

**Comment by yurievangelista** [comment]
I've opened #31 which is pretty simple right now. Let me know what you think about it.

**Comment by dizco** [comment]
Published v1.2.0 which fixes this. Thank you!
