### ISSUE TITLE
Scroll to bottom once div is large enough to need scrollbars

### ISSUE THREAD

**Issue by depiction** [dizco/react-scrollable-feed#34]
**Describe the bug**
If the scrollable div doesn't initially have enough content to show a scrollbar, but new items are added later to require a scrollbar, users aren't automatically scrolled to the bottom.

**To Reproduce**
1. Go to the demo page (https://dizco.github.io/react-scrollable-feed/).
2. In developer tools, change .scrollable-wrapper to have a fixed height of 300px instead of a max-height of 300px. Verify that no scrollbars appear.
3. Add new items until a scrollbar appears.

**Expected behavior**
Once a scrollbar appears, users should be scrolled to the bottom. Once at the bottom, users should be able to scroll back up with their scroll position not changing when new items are added.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome

**Additional context**
`forceScroll` could be set to true, however that would also force scrolling to the bottom if a user scrolls up later.

**Comment by dizco** [comment]
I can confirm the bug. I'm not quite sure what might be causing this... I'll probably have time to investigate this in a few weeks, but until then if anybody wants to give it a shot please be my guest :)

**Comment by cha0s** [comment]
Just wanted to chime in that I found this, and while I haven't developed a solution (yet?), I found that bumping up `viewableDetectionEpsilon` helped (16 in my case).

**Comment by dizco** [comment]
Thanks @cha0s, good to know that there is a workaround. I still don't have time to investigate this for at least 2 weeks.

**Comment by dizco** [comment]
Please try v1.3.0
