### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by PainKKKiller** [dizco/react-scrollable-feed#38]
Hello!
Nice project, but I've read documentation and really wondered is it possible to make infinite scroll with with component? In usual onScroll event I can use e.target.scrollTop === 0 to determine if scroll at top, to fetch new items from server.  But in this component I've got only isAtBottom parameter. If make infinite scroll possible, at least it should be in examples.

**Comment by dizco** [comment]
Hi!
The core of this library is very straight-forward, you should be able to copy-paste it and adapt it to fit your infinite scroll needs easily: https://github.com/dizco/react-scrollable-feed/blob/master/src/index.tsx
I'm open to a PR that would properly support infinite scrolling, but it's not in my short-term plans to support this. Thank you :)
