### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by edemaine** [dizco/react-scrollable-feed#42]
**Describe the bug**
Could you add React 17 as a valid dependency, or perhaps more generally, allow react>=15?

**To Reproduce**
1. Use npm 6 (e.g. 6.14.11)
2. `npm install react@17 react-scrollable-feed`
3. See error:
   `npm WARN react-scrollable-feed@1.3.0 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.`

I imagine npm 7 produces a (different) warning.

**Comment by dizco** [comment]
Hi @edemaine thanks for the comment, I unfortunately don't have much time to test this right now... And will probably be at least 1 month before I can have a look. I am opening this up to anybody who would like to contribute.

**Comment by dizco** [comment]
Please try v1.3.1

**Comment by edemaine** [comment]
Works well, thanks!
