### ISSUE TITLE
Increasing height of browser reveals white space at bottom of scrollable area on Safari.

### ISSUE THREAD

**Issue by dominicboston** [dizco/react-scrollable-feed#45]
**Describe the bug**
Scrolling down, then expanding the browsers height produces white space within scrollable area.

This seems to be only an issue on safari. I would like to try to solve this myself but i'm not exactly sure what is causing this.
Another thing I've noticed is every now and again (seemingly randomly), the scrollable area jumps up adding white space in the same way. I'm not sure if these two problems are related but if this first is fixed, it may solve the second. 

**To Reproduce**
1. Open Demo on Safari 11.2.3
2. Inspect CSS
3. Add height:100vh to <div class="card-body scrollable-wrapper pt-0 pb-0 mt-2">
4. Add enough items to overfill the screen (25)
5. Change the height of the window to reveal only 5 items.
6. Scroll to bottom of message window.
7. Expand height to reveal white space 

**Expected behavior**
Message to stick to bottom of window revealing new items

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser [safari]
 - Version [11.2.3]

**Comment by dizco** [comment]
Hi @dominicboston, thank you for the bug report.
That is a very strange behavior, and I don't seem to be able to reproduce it on Chrome on Windows. I'm thinking the issue must be related to some CSS property which might be behaving differently on Safari, but it's hard to tell which one. If you find more information about this please let me know!

**Comment by dizco** [comment]
I will close this bug, if anybody has more information please reopen.
