### ISSUE TITLE
Images loading in chat are not taken into account by the component when determining scroll position

### ISSUE THREAD

**Issue by jaxomlotus** [dizco/react-scrollable-feed#57]
**Describe the bug**
When a user posts an image in chat, the component will not re-render it's position after the image loads. So the user will need to manually scroll down to the bottom of the image to resume chatting.

**To Reproduce**
1. Try React-Scrollable-Feed in any chatroom implementation that supports image posting
2. Scroll to the bottom
3. Add an image to chat
4. See how the user is no longer scrolled to the bottom of chat and chat is now paused

**Expected behavior**
I would expect the chat to move to the bottom of the image, if the image was previously the bottom of the page.

**Screenshots**

**Desktop (please complete the following information):**
all
- but tested on windows 10, chrome

**Smartphone (please complete the following information):**
iOS

**Additional context**

**Comment by dizco** [comment]
Hi, unfortunately I dont have the time to investigate this issue. It might be a bug, but if you can provide a live repro that would also help triage... If anybody wants to have a shot at a fix, please feel free to do so.
