### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by zmaniacz** [dizco/react-scrollable-feed#69]
Are there any plans to support React 18?

**Comment by dizco** [comment]
Hi @zmaniacz 
Its not in my short term plans. If you want to submit a PR for this feel free to do so!

**Comment by troels-athenas** [comment]
I'm using this with React 18 ... seems to work fine?

**Comment by troels-athenas** [comment]
https://github.com/dizco/react-scrollable-feed/pull/77

**Comment by dizco** [comment]
Fixed in 1.3.2
