### ISSUE TITLE
forceScroll property returning a type error

### ISSUE THREAD

**Issue by jeffsummer08** [dizco/react-scrollable-feed#87]
**Describe the bug**
The forceScroll property is not assignable to type "IntrinsicAttributes"

**Screenshots**
![image](https://user-images.githubusercontent.com/86799981/230775507-741ab4ea-c564-4f53-9b0f-e6fb62977d0d.png)

**Desktop:**
 - OS: Windows 10
 - VSCode
 - TSX (Typescript React)

**Comment by dizco** [comment]
Fixed in 2.0.1
