### ISSUE TITLE
Pagination to top

### ISSUE THREAD

**Issue by alsam2009** [dizco/react-scrollable-feed#96]
Tnx for your usefull work! But what about pagination, when old messages is arriving by portions after scroll to top?

**Comment by dizco** [comment]
Hi, I'm not sure I understand the issue. Could you please provide a code sample describing your issue?

**Comment by alsam2009** [comment]
Oh, sorry. There is not issue indeed. It was a question. ) 
Ex: when you are scrolling to top, next part of data particule downloading and must be render into DOM. So, I asked how use your component in infinite scroll to top, not to bottom as usually.  Please, clarify this point. )

**Comment by dizco** [comment]
I don't think this feature is supported by this package right now. It supports only detection of the bottom. But I wouldn't really mind if someone submitted a PR to implement this.
