### ISSUE TITLE
Event in onScroll

### ISSUE THREAD

**Issue by mrtk0y** [dizco/react-scrollable-feed#98]
**Is your feature request related to a problem? Please describe.**
I got problem with the library is lack of current position in div
While i need the div constant at the bottom, i need to know when it's scrolling down away from top to animation the header of div

**Describe the solution you'd like**
Add default event onScroll in onScroll of library to use scrollTop, offsetTop and etc

**Describe alternatives you've considered**

**Comment by dizco** [comment]
I'm sorry I honestly don't understand your issue. If this is a bug report, please describe how to reproduce it.

If its a feature request, please submit a pull request so that I can understand the suggestion.
